apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment  # Nome do Deployment
  annotations:
    autor: Rodrigo Mahlow 
spec:  
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: rmahlow/fiaphackatoonidentityapi:latest        
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8081"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: DefaultConnection
        - name: ElasticSettings__ApiKey
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: ApiKey
        - name: ElasticSettings__CloudId
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: CloudId
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: SecretJWT
        - name: RabbitMq__UserName
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: User
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: Password              
        - name: RabbitMq__HostName
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "Server"
        - name: RabbitMq__Port
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "Port"                              
        - name: RabbitMq__QueueNameClienteCreate
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "QueueNameClienteCreate"   
        - name: RabbitMq__QueueNameClienteUpdate
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "QueueNameClienteUpdate"   
        - name: RabbitMq__QueueNameEmployeeCreate
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "QueueNameEmployeeCreate"   
        - name: RabbitMq__QueueNameEmployeeUpdate
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "QueueNameEmployeeUpdate"                                                                         
        
       