apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment  # Nome do Deployment
  annotations:
    autor: Rodrigo Mahlow 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: rmahlow/fiaphackatoonidentityapi:latest
        ports:
        - containerPort: 8080 
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: SecretJWT
        - name: RabbitMq__UserName
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: User
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: identity-api-secrets
              key: Password              
        - name: RabbitMq__HostName
          valueFrom:
            configMapKeyRef: 
              name: identity-api-configmap
              key: "Server"        
        
       