apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api-deployment  # Nome do Deployment
  annotations:
    autor: Rodrigo Mahlow 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: rmahlow/fiaphackatoonidentityapi:latest
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi     
       